### ISSUE TITLE
@qio/prelude not published

### ISSUE THREAD

**Issue by mikearnaldi** [tusharmath/fearless-io#14]
Package `@qio/core` depends on non published `@qio/prelude`

**Comment by tusharmath** [comment]
Thanks! This is fixed.

https://www.npmjs.com/package/@qio/prelude

**Comment by mikearnaldi** [comment]
Great! by the way very nice work going on here!

**Comment by tusharmath** [comment]
Thanks :)

Tushar Mathur
tusharmath.com ( https://tusharmath.com )
