### ISSUE TITLE
Catch handlers are executed out of order

### ISSUE THREAD

**Issue by Avaq** [tusharmath/fearless-io#7]
# Introduction

Hi! I was having a look at your code; I always like to see new solutions to the async problem.

I like the way you did `evaluate`! I've always wanted Fluture to have an elegant state machine like that. ;)

I noticed a theoretical flaw however, so I set out to test it, and found what I believe to be an issue.

# Steps to reproduce

```js
const io = FIO.of('input')
.catch(x => FIO.of(['catch', x]))
.chain(x => FIO.reject(['chain', x]))

defaultRuntime()
.execute(io, x => console.log('res', x), x => console.log('rej', x))
```

# Expected result

```js
rej [ "chain", "input" ]
```

I expect the code to have a flow like:

1. Resolve with `input`
2. Ignore the `catch`, because the IO is resolved
3. Execute the `chain`, and assume rejected state
4. Run `onError`, because the final IO was rejected

# Actual result

```js
res [ "catch", [ "chain", "input" ] ]
```

What actually happened is:

1. Resolve with `input`
2. Register the `catch` handler for later
3. Execute the `chain`, and assume rejected state
4. Run the registered `catch` handler
5. Run `onSuccess`, because the final IO was resolved

-----

I'm not sure if this behaviour is by design. It seems to be a bug, as I believe it causes type inconsistencies. However, it is very similar to the behaviour of `Bluebird.finally`, and it might've been what you were going for.

**Comment by tusharmath** [comment]
Thanks a ton for reporting the issue @Avaq! I have taken a lot of cues from your library while working on FIO & have come to realize it's a lot of hard work, so hats off to you for maintaining Fluture.

I have fixed this issue here - https://github.com/tusharmath/fearless-io/pull/6/files#diff-70c5080bf8ab6a2603b068e6defe50afR147

This is still WIP :)
